openapi: 3.0.3
info:
  title: Brain Rot Chronicles - Auth & User Service
  description: >
    Service monolithique (soupir) pour la gestion de l'authentification ET des utilisateurs.
    On gère ici les comptes "Skibidi", les tokens, et les profils.
  version: 1.1.0
servers:
  - url: http://localhost:4007/api/v1/auth
    description: Serveur de développement local

paths:
  /register:
    post:
      summary: Créer un nouveau compte joueur
      tags: [Inscription]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Joueur créé avec succès. Bienvenue dans la matrice.
        '400':
          $ref: '#/components/responses/BadRequestError'
        '409':
          description: Conflit (Nom d'utilisateur ou email déjà pris).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          $ref: '#/components/responses/InternalError'

  /login:
    post:
      summary: Authentifier un utilisateur et générer un jeton
      tags: [Session]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentification réussie.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Identifiants invalides (Pas assez de Rizz).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          $ref: '#/components/responses/InternalError'

  /logout:
    post:
      summary: Déconnexion (Révocation du token)
      description: Invalide le Refresh Token en base de données et ajoute l'Access Token à la blacklist.
      tags: [Session]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '204':
          description: Déconnexion réussie.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'

  /refresh:
    post:
      summary: Rafraîchir un jeton expiré
      tags: [Session]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Nouveau jeton généré.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Refresh Token invalide ou expiré.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          $ref: '#/components/responses/InternalError'

  /validate:
    get:
      summary: Vérifier la validité d'un jeton (Utilisé par la Gateway)
      tags: [Interne]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Le jeton est valide.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserIdentity'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'

  /users/me:
    get:
      summary: Récupérer son profil joueur
      description: Retourne les informations du compte connecté.
      tags: [Utilisateur]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profil récupéré.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
    patch:
      summary: Mettre à jour son profil (Glow Up)
      tags: [Utilisateur]
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Profil mis à jour.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserRegistration:
      type: object
      required: [username, password, email]
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
          pattern: '^[a-zA-Z0-9_]+$'
          description: "Nom d utilisateur unique (alphanumérique et underscores uniquement)"
          example: "SkibidiSlayer67"
        email:
          type: string
          format: email
          example: "tanguy@aura.fr"
        isSigma:
          type: boolean
          example: false
        password:
          type: string
          format: password
          minLength: 12
          description: "Doit contenir au moins 12 caractères pour résister aux attaques brute-force."

    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username: { type: string }
        password: { type: string }

    RefreshTokenRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string
          description: Le refresh token.

    AuthToken:
      type: object
      properties:
        accessToken: { type: string }
        refreshToken: { type: string }
        expiresIn: { type: integer, example: 3600 }

    UserIdentity:
      type: object
      properties:
        userId: { type: string, format: uuid }
        username: { type: string }

    UserResponse:
      type: object
      required: [id, username, email, isSigma]
      properties:
        id: { type: string, format: uuid }
        username: { type: string }
        email: { type: string, format: email }
        isSigma: { type: boolean }
        createdAt: { type: string, format: date-time }

    UserUpdate:
      type: object
      properties:
        email: { type: string, format: email }
        isSigma: { type: boolean, description: "Uniquement modifiable par un admin (ou triche)" }

    ErrorModel:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          example: "AUTH_FAILED"
        message:
          type: string
          example: "Identifiants invalides."
        timestamp:
          type: string
          format: date-time

  responses:
    BadRequestError:
      description: Requête invalide.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    UnauthorizedError:
      description: Non autorisé / Token invalide.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    InternalError:
      description: Erreur interne du serveur.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'